In [10]:
import pickle
import numpy as np
from os.path import join
import matplotlib.pyplot as plt
from keras.preprocessing import image
from PIL import Image
%matplotlib inline

In [7]:
def load_data_from_pkl(data_path):
  """
  Load data from pickle file.
  """
  with open(data_path, 'rb') as f:
    print('Loading {}...'.format(f.name))
    return pickle.load(f)

In [ ]:
d_2 = load_data_from_pkl('../../data/radicals/formatted/0.p')

In [ ]:
d_0.shape

In [ ]:
for d in d_0[1500:1510]:
    plt.imshow(image.array_to_img(d).convert('RGB'))
    plt.show()

In [ ]:
d_0[0]

In [5]:
x_train = load_data_from_pkl('../../data/preprocessed_data/radical/x_train.p')
y_train = load_data_from_pkl('../../data/preprocessed_data/radical/y_train.p')
x_valid = load_data_from_pkl('../../data/preprocessed_data/radical/x_valid.p')
y_valid = load_data_from_pkl('../../data/preprocessed_data/radical/y_valid.p')
x_test = load_data_from_pkl('../../data/preprocessed_data/radical/x_test.p')
y_test = load_data_from_pkl('../../data/preprocessed_data/radical/y_test.p')

Loading ../../data/preprocessed_data/radical/x_train.p...
Loading ../../data/preprocessed_data/radical/y_train.p...
Loading ../../data/preprocessed_data/radical/x_valid.p...
Loading ../../data/preprocessed_data/radical/y_valid.p...
Loading ../../data/preprocessed_data/radical/x_test.p...
Loading ../../data/preprocessed_data/radical/y_test.p...


In [ ]:
for i in range(30):
    plt.imshow(image.array_to_img(x_train[i]).convert('RGB'))
    print(y_train[i])
    plt.show()

In [13]:
def get_batches(x, y, batch_size):
  """Split features and labels into batches."""
  for start in range(0, len(x), batch_size):
    end = start + batch_size
    yield x[start:end], y[start:end]

In [14]:
x = list(range(50))
y = list(range(20, 70))

In [15]:
bg = get_batches(x, y, 8)

In [22]:
next(bg)

([48, 49], [68, 69])

In [24]:
xn= np.array(x)

In [25]:
xn[44:53]

array([44, 45, 46, 47, 48, 49])

In [75]:
a = np.array([[[1, 2], 
               [3, 4]], 
              [[5, 6], 
               [7, 8]]])
np.expand_dims(np.zeros_like(a[0]), axis=0)

array([[[0, 0],
        [0, 0]]])

In [81]:
a = np.append(a, np.expand_dims(np.zeros_like(a[0]), axis=0), axis=0)
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [66]:
np.append(np.array([[[1, 2], [2, 4], [3, 6]], [[4, 7], [5, 8], [6, 9]]]), 
          np.array([[[7, 1], [8, 4], [9, 5]]]), axis=0)

array([[[1, 2],
        [2, 4],
        [3, 6]],

       [[4, 7],
        [5, 8],
        [6, 9]],

       [[7, 1],
        [8, 4],
        [9, 5]]])

In [95]:
np.concatenate([], np.array([[1, 2], [2, 3], [3, 5]]))

TypeError: only integer scalar arrays can be converted to a scalar index

In [89]:
np.concatenate((np.array([ 1.,  2.,  3.]), np.array([1, 2, 3])))

array([ 1.,  2.,  3.,  1.,  2.,  3.])

In [11]:
source_data_path = join('../../data/source_data', 'mnist')
x = load_data_from_pkl(join(source_data_path, 'train_images.p'))
y = load_data_from_pkl(join(source_data_path, 'train_labels.p'))
x_test = load_data_from_pkl(join(source_data_path, 'test_images.p'))
y_test = load_data_from_pkl(join(source_data_path, 'test_labels.p'))

Loading ../../data/source_data/mnist/train_images.p...


Loading ../../data/source_data/mnist/train_labels.p...
Loading ../../data/source_data/mnist/test_images.p...
Loading ../../data/source_data/mnist/test_labels.p...


In [13]:
y

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)